<h1>13. More Adventures in OOP</h1>
<h2>11/2/2020</h2>

<h2>13.0 Last Time...</h2>
<ul>
    <li>A class can be created using a <b>class</b> statement followed by the name of the class.</li>
    <li>Methods within a class definition are created using a <b>def</b> statement.</li>
    <li><b>__init__</b> is typically the first method defined and is used to initialize the core features of the class.</li>
</ul>


<h2>13.1 OOP Example: Creating a Bibliography</h2>

Let's create a new class called <b>Article</b> that's similar to our book class from last time, but stores a scientific journal article instead of a book, and writes the bibiliography entry accordingly.

In [ ]:
# Start by defining a new class. (Remember, you need the 'object' argument.)

class Article(object):
    def __init__(self, authorlast, authorfirst, \
                articletitle, journaltitle, \
                volume, pages, year):
        self.authorlast = authorlast
        self.authorfirst = authorfirst
        self.articletitle = articletitle
        self.journaltitle = journaltitle
        self.volume = volume
        self.pages = pages
        self.year = year
        
        # Let's create the make_authoryear and write_bib_entry methods from before.
        
    def make_authoryear(self):
        self.authoryear = self.authorlast \
                        + ' (' + self.year + ')'
        
    def write_bib_entry(self):
        return self.authorlast \
            + ', ' + self.authorfirst \
            + ' (' + self.year + '): ' \
            + '"' + self.articletitle + '", ' \
            + self.journaltitle + ', ' \
            + self.volume + ', ' \
            + self.pages + '.'

In [ ]:
# And a test!

tornado = Article("Brooks", "Harold" \
            , "On the relationship of tornado path length and width to intensity" \
            , "Weather and Forecasting" \
            , "19", "310-319", "2004")
print(tornado)
print(tornado.write_bib_entry())

Let's also bring <b>Book</b> and our two instances of Book back from last week:

In [ ]:
class Book(object):
    
    def __init__(self, authorlast, authorfirst, \
                title, place, publisher, year):
        self.authorlast = authorlast
        self.authorfirst = authorfirst
        self.title = title
        self.place = place
        self.publisher = publisher
        self.year = year
    
    def write_bib_entry(self):        
        return self.authorlast \
            + ', ' + self.authorfirst \
            + ', ' + self.title \
            + ', ' + self.place \
            + ': ' + self.publisher + ', '\
            + self.year + '.'

beauty = Book("Dubay","Thomas" \
             , "The Evidential Power of Beauty" \
             , "San Francisco" \
             , "Ignatius Press", "1999")

pynut = Book("Martelli", "Alex" \
            , "Python in a Nutshell" \
            , "Sebastopol, CA" \
            , "O'Reilly Media, Inc.", "2003")

Let's say we have a series of instances of the Book and Article classes that we want to pull together into one big bibliography. We'll create a new class called <b>Bibliography</b> for this task, and within Bibliography's definition will be two modules: one that initializes the class with everything we need, and one that sorts all entries alphabetically.

To do this, we'll need some additional tools. One useful package to import here is called <b>operator</b>, which contains a useful function called <b>attrgetter</b>, which will pull a list of attributes out of an item in question. There are other ways of doing the same thing, but operator.attrgetter() will save us a lot of time! 

We'll also want to make use of <b>sorted()</b>, which is a function that sorts all entries (either alphabetically or numerically) according to a key we specify, which in this case will be the last name and the first name of the author (just in case we have multiple authors with the same last name).

In [ ]:
# We'll need the operator package.

import operator as op

# Define our Bibliography class.

class Bibliography(object):
    
    # Initialize the class.
    def __init__(self, entrieslist):
        self.entrieslist = entrieslist
        
    # Sort the entries alphabetically.
    def sort_entries_alpha(self):
        self.entrieslist = sorted(self.entrieslist, \
                                 key=op.attrgetter('authorlast',
                                                        'authorfirst'))
    
    # Now, write a bibliography in alphabetical order.
    def write_bibliog_alpha(self):
        self.sort_entries_alpha()
        output = ''
        for ientry in self.entrieslist:
            output = output + ientry.write_bib_entry() + '\n\n'
        return output

In [ ]:
a = Bibliography([beauty,pynut,tornado])
b = a.write_bibliog_alpha()
print(b)

Why did we bother doing this? Because it really highlights the power of OOP over traditional, procedural programming. In a lot of languages, we'd have to write a function to format every source entry correctly, depending on the source type (e.g., article or book), which would result in a tree of <b>if</b> tests.

Another big advantage? Adding another source type would require <b>no changes or additions to existing code</b>, just a new class definition.

<h2>13.2 OOP Example: Creating a Class for Geoscience Work</h2>

Let's work through another application: as an example, we'll define a class called <b>SurfaceDomain</b> that describes surface domain instances. A domain would be a land/ocean surface where the spatial extent is described by a latitude-longitude grid. We'll instantiate the class by providing a vector of longitudes and latitudes; our surface domain will be a regular grid based on those vectors. We can then assign surface parameters (e.g., elevation, temperature, roughness, etc.) as instance attributes.

It may be helpful here to think of how best to represent a latitude-longitude grid in code. Let's look at the following example:

In [ ]:
# Let's say we have 5 longitude values and 4 latitude values.
# We want something that's going to look like the following:

# Longitude should look like this:

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

# Latitude should look like this:

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]

There's a function in NumPy built in for this called <b>meshgrid</b>: given a longitude array and a latitude array, it will create a nice grid combining the two.

Let's start our class definition.

In [ ]:
import numpy as np

class SurfaceDomain(object):
    def __init__(self, lon, lat):
        
        # Let's make sure that latitude and longitude 
        # are in array format.
        self.lon = np.array(lon)
        self.lat = np.array(lat)
        [xall, yall] = np.meshgrid(self.lon, self.lat)
        self.lonall = xall
        self.latall = yall
        del xall, yall

We can then begin to manipulate elements of this domain individually or collectively (e.g., interpolation, etc.).

In [ ]:
lon = [0,1,2,3,4]
lat = [0,1,2,3]

a = SurfaceDomain(lon, lat)
print(a.lonall)
print(a.latall)

<h2>13.3 Take-Home Points</h2>
<ul>
    <li>The <b>operator</b> package enables us to use a function called <b>attrgetter()</b> to grab attribute information from various classes.</li>
    <li>The <b>sorted()</b> function lets us sort data alphabetically or numerically as needed.</li>
    <li>NumPy's <b>meshgrid()</b> module lets us create a grid from lat/lon vectors.</li> 
</ul>