In [19]:
import os
import netCDF4 as nc4
import numpy as np
import datetime as dt
from matplotlib.dates import DateFormatter, MonthLocator

# For plotting
%matplotlib
import matplotlib as mpl
import matplotlib.pyplot as plt

Using matplotlib backend: TkAgg


In [20]:
STRA = 1
CONV = 2
OTHER = 3

NHW = 0
NHC = 1
NHE = 2

In [21]:
#User inputs
indir_v05 = '/home/disk/bob/gpm/nht_ku/classify/ex_data_v05'
indir_ite132 = '/home/disk/bob/gpm/nht_ku/classify/ex_data_ite132'
indir_ite601 = '/home/disk/bob/gpm/nht_ku/classify/ex_data_ite601'

years = ['2015','2016']

In [4]:
#Declare output arrays
stra_counts_v05 = np.zeros((3,12),dtype=int)
stra_counts_v05_uw = np.zeros((3,12),dtype=int)
stra_counts_ite132 = np.zeros((3,12),dtype=int)
stra_counts_ite601 = np.zeros((3,12),dtype=int)

conv_counts_v05 = np.zeros((3,12),dtype=int)
conv_counts_v05_uw = np.zeros((3,12),dtype=int)
conv_counts_ite132 = np.zeros((3,12),dtype=int)
conv_counts_ite601 = np.zeros((3,12),dtype=int)

other_counts_v05 = np.zeros((3,12),dtype=int)
other_counts_v05_uw = np.zeros((3,12),dtype=int)
other_counts_ite132 = np.zeros((3,12),dtype=int)
other_counts_ite601 = np.zeros((3,12),dtype=int)

In [24]:
# array for datetime objects used for x-axis labels
x_values = []

In [26]:
for iyear in years:
    print 'year=',iyear
    if iyear == '2015':
        months = ['04','05','06','07','08','09','10','11','12']
    else:
        months = ['01','02','03']
    for idx, imonth in enumerate(months):
        if iyear == '2015':
            index = idx
        else:
            index = idx+9
        print 'month=',imonth,' idx=',idx,' index=',index
        # turn month into datetiem object
        curr_month = dt.datetime(int(iyear),int(imonth),1)
        x_values.append(curr_month)

year= 2015
month= 04  idx= 0  index= 0
month= 05  idx= 1  index= 1
month= 06  idx= 2  index= 2
month= 07  idx= 3  index= 3
month= 08  idx= 4  index= 4
month= 09  idx= 5  index= 5
month= 10  idx= 6  index= 6
month= 11  idx= 7  index= 7
month= 12  idx= 8  index= 8
year= 2016
month= 01  idx= 0  index= 9
month= 02  idx= 1  index= 10
month= 03  idx= 2  index= 11


In [6]:
for iyear in years:
    print 'year=',iyear
    if iyear == '2015':
        months = ['04','05','06','07','08','09','10','11','12']
    else:
        months = ['01','02','03']
    for idx, imonth in enumerate(months):
        if iyear == '2015':
            index = idx
        else:
            index = idx+9
        print 'month=',imonth,' idx=',idx,' index = ',index
        # turn month into datetime object
        curr_month = dt.datetime(int(iyear),int(month),1)
        x_values.append(cur_month)
        for fname in os.listdir(indir_v05+'/'+iyear+'/'+imonth):
            #print fname
            #open fname and read rain_type and rain_type_uw
            ncid = nc4.Dataset(indir_v05+'/'+iyear+'/'+imonth+'/'+fname,'r')
            rt = np.array(ncid.variables['rain_type'])
            rt_uw = np.array(ncid.variables['rain_type_uw'])
            ncid.close()
            if fname.endswith('NHW.nc'):
                #unique, counts = np.unique(rt, return_counts=True)
                stra_counts_v05[NHW,index] += np.count_nonzero(rt == STRA)
                conv_counts_v05[NHW,index] += np.count_nonzero(rt == CONV)
                other_counts_v05[NHW,index] += np.count_nonzero(rt == OTHER)
                stra_counts_v05_uw[NHW,index] += np.count_nonzero(rt_uw == STRA)
                conv_counts_v05_uw[NHW,index] += np.count_nonzero(rt_uw == CONV)
                other_counts_v05_uw[NHW,index] += np.count_nonzero(rt_uw == OTHER)
            elif fname.endswith('NHC.nc'):
                #unique, counts = np.unique(rt, return_counts=True)
                stra_counts_v05[NHC,index] += np.count_nonzero(rt == STRA)
                conv_counts_v05[NHC,index] += np.count_nonzero(rt == CONV)
                other_counts_v05[NHC,index] += np.count_nonzero(rt == OTHER)
                stra_counts_v05_uw[NHC,index] += np.count_nonzero(rt_uw == STRA)
                conv_counts_v05_uw[NHC,index] += np.count_nonzero(rt_uw == CONV)
                other_counts_v05_uw[NHC,index] += np.count_nonzero(rt_uw == OTHER)
            elif fname.endswith('NHE.nc'):
                #unique, counts = np.unique(rt, return_counts=True)
                stra_counts_v05[NHE,index] += np.count_nonzero(rt == STRA)
                conv_counts_v05[NHE,index] += np.count_nonzero(rt == CONV)
                other_counts_v05[NHE,index] += np.count_nonzero(rt == OTHER)
                stra_counts_v05_uw[NHE,index] += np.count_nonzero(rt_uw == STRA)
                conv_counts_v05_uw[NHE,index] += np.count_nonzero(rt_uw == CONV)
                other_counts_v05_uw[NHE,index] += np.count_nonzero(rt_uw == OTHER)
        for fname in os.listdir(indir_ite132+'/'+iyear+'/'+imonth):
            #print fname
            #open fname and read rain_type
            ncid = nc4.Dataset(indir_ite132+'/'+iyear+'/'+imonth+'/'+fname,'r')
            rt = np.array(ncid.variables['rain_type'])
            ncid.close()
            if fname.endswith('NHW.nc'):
                #unique, counts = np.unique(rt, return_counts=True)
                stra_counts_ite132[NHW,index] += np.count_nonzero(rt == STRA)
                conv_counts_ite132[NHW,index] += np.count_nonzero(rt == CONV)
                other_counts_ite132[NHW,index] += np.count_nonzero(rt == OTHER)
            elif fname.endswith('NHC.nc'):
                #unique, counts = np.unique(rt, return_counts=True)
                stra_counts_ite132[NHC,index] += np.count_nonzero(rt == STRA)
                conv_counts_ite132[NHC,index] += np.count_nonzero(rt == CONV)
                other_counts_ite132[NHC,index] += np.count_nonzero(rt == OTHER)
            elif fname.endswith('NHE.nc'):
                #unique, counts = np.unique(rt, return_counts=True)
                stra_counts_ite132[NHE,index] += np.count_nonzero(rt == STRA)
                conv_counts_ite132[NHE,index] += np.count_nonzero(rt == CONV)
                other_counts_ite132[NHE,index] += np.count_nonzero(rt == OTHER)

year= 2015
month= 04  idx= 0  index =  0
month= 05  idx= 1  index =  1
month= 06  idx= 2  index =  2
month= 07  idx= 3  index =  3
month= 08  idx= 4  index =  4
month= 09  idx= 5  index =  5
month= 10  idx= 6  index =  6
month= 11  idx= 7  index =  7
month= 12  idx= 8  index =  8
year= 2016
month= 01  idx= 0  index =  9
month= 02  idx= 1  index =  10
month= 03  idx= 2  index =  11


In [42]:
stra_counts_v05
#stra_counts_v05_uw
#stra_counts_ite132
#conv_counts_v05
#conv_counts_v05_uw
#conv_counts_ite132
#other_counts_v05
#other_counts_v05_uw
#other_counts_ite132

array([[230566, 342783, 291199, 360649, 295992, 304768, 314521, 255346,
        254195, 190648, 151150, 126675],
       [ 85262, 164289, 136256, 158177, 193338, 159661, 164906, 138662,
         75556,  41438,  51146, 117794],
       [205521, 236524, 332322, 270239, 346212, 337228, 275823, 291836,
        171625,  99733,  90656,  93466]])

In [45]:
# plot convective output
fig = plt.figure()
#plt.xlim(1, 12)
#plt.ylim();
plt.plot(x_values,conv_counts_v05[0,:], '-', color='black', label='NHW_v05')
plt.plot()
plt.plot(x_values,conv_counts_v05_uw[0,:], '-', color='red', label='NHW_v05_uw')
plt.plot()
plt.plot(x_values,conv_counts_ite132[0,:], '-', color='blue', label='NHW_ite132')
plt.plot()
plt.plot(x_values,conv_counts_v05[1,:], ':', color='black', label='NHC_v05')
plt.plot()
plt.plot(x_values,conv_counts_v05_uw[1,:], ':', color='red', label='NHC_v05_uw')
plt.plot()
plt.plot(x_values,conv_counts_ite132[1,:], ':', color='blue', label='NHC_ite132')
plt.plot()
plt.plot(x_values,conv_counts_v05[2,:], '--', color='black', label='NHE_v05')
plt.plot()
plt.plot(x_values,conv_counts_v05_uw[2,:], '--', color='red', label='NHE_v05_uw')
plt.plot()
plt.plot(x_values,conv_counts_ite132[2,:], '--', color='blue', label='NHE_ite132')
plt.plot()
plt.legend()
plt.xlabel('months')
plt.ylabel('pixel counts')
plt.title('Convective Counts - Near Equatorial, Northern Hemisphere')
plt.tight_layout()

In [86]:
# plot convective NHW output
fig = plt.figure()
ax = fig.gca()
#plt.xlim(1, 12)
#plt.ylim();
plt.plot(x_values,conv_counts_v05[0,:], '-', color='black', label='NHW_v05')
plt.plot()
plt.plot(x_values,conv_counts_v05_uw[0,:], '-', color='red', label='NHW_v05_uw')
plt.plot()
plt.plot(x_values,conv_counts_ite132[0,:], '-', color='blue', label='NHW_ite132')
plt.plot()
plt.grid(linestyle=":")
plt.legend()
# Set which months to put tickmarks at
#ax.xaxis.set_major_locator( MonthLocator(0,1,2,3,4,5,6,7,8,9,10,11))
#ax.xaxis.set_major_locator(xmajor_locator)
ax.xaxis.set_major_locator(xminor_locator)
#set format of months (YYYYMM)
ax.xaxis.set_major_formatter( DateFormatter('%Y%m') )
#rotate label text to vertical
#plt.setp(plt.xticks()[1], rotation=90)
plt.xlabel('months')
plt.ylabel('pixel counts')
plt.title('Convective Counts - NHW')
plt.tight_layout()

NameError: name 'xminor_locator' is not defined

In [29]:
plt.xticks()

(array([ 735719.,  735780.,  735842.,  735903.,  735964.,  736024.]),
 <a list of 6 Text xticklabel objects>)

In [46]:
# plot convective NHC output
fig = plt.figure()
#plt.xlim(1, 12)
#plt.ylim();
plt.plot(x_values,conv_counts_v05[1,:], '-', color='black', label='NHC_v05')
plt.plot()
plt.plot(x_values,conv_counts_v05_uw[1,:], '-', color='red', label='NHC_v05_uw')
plt.plot()
plt.plot(x_values,conv_counts_ite132[1,:], '-', color='blue', label='NHC_ite132')
plt.plot()
plt.legend()
plt.xlabel('months')
plt.ylabel('pixel counts')
plt.title('Convective Counts - NHC')
plt.tight_layout()

In [47]:
# plot convective NHE output
fig = plt.figure()
#plt.xlim(1, 12)
#plt.ylim();
plt.plot(x_values,conv_counts_v05[2,:], '-', color='black', label='NHE_v05')
plt.plot()
plt.plot(x_values,conv_counts_v05_uw[2,:], '-', color='red', label='NHE_v05_uw')
plt.plot()
plt.plot(x_values,conv_counts_ite132[2,:], '-', color='blue', label='NHE_ite132')
plt.plot()
plt.legend()
plt.xlabel('months')
plt.ylabel('pixel counts')
plt.title('Convective Counts - NHE')
plt.tight_layout()

In [70]:
percent_diffs = (conv_counts_v05_uw[0,:]-conv_counts_ite132[0,:])/np.asfarray(conv_counts_v05_uw[0,:])
print conv_counts_v05_uw[0,:]
print conv_counts_ite132[0,:]
print conv_counts_v05_uw[0,:]-conv_counts_ite132[0,:]
print percent_diffs

[157516 176305 176694 205827 187043 184852 188927 182809 185480 139961
 121342 113448]
[152770 169868 171668 198498 180531 178287 181640 177555 179614 136379
 118250 111004]
[4746 6437 5026 7329 6512 6565 7287 5254 5866 3582 3092 2444]
[ 0.03013027  0.03651059  0.02844466  0.03560757  0.03481552  0.0355149
  0.03857045  0.02874038  0.03162605  0.02559284  0.0254817   0.02154291]


In [76]:
# plot % diffs between v05_uw and ite132
fig = plt.figure()
ax = fig.gca()
ax.set_xticks(numpy.arange(0, 12, 1))
plt.plot(x_values,(conv_counts_v05_uw[0,:]-conv_counts_ite132[0,:])/np.asfarray(conv_counts_v05_uw[0,:])*100.,'-',color='black',label='NHW')
plt.plot()
plt.plot(x_values,(conv_counts_v05_uw[1,:]-conv_counts_ite132[1,:])/np.asfarray(conv_counts_v05_uw[1,:])*100.,'-',color='red',label='NHC')
plt.plot()
plt.plot(x_values,(conv_counts_v05_uw[2,:]-conv_counts_ite132[2,:])/np.asfarray(conv_counts_v05_uw[2,:])*100.,'-',color='blue',label='NHE')
plt.plot()
plt.grid()
plt.legend()
plt.xlabel('months')
plt.ylabel('% diff (v05_uw-ite132)/v05_uw')
plt.title('Percent Diff in Conv Counts - NHT (0-20N,180W-180E)')
plt.tight_layout()

In [49]:
# plot stratiform output
fig = plt.figure()
#plt.xlim(1, 12)
#plt.ylim();
plt.plot(x_values,stra_counts_v05[0,:], '-', color='black', label='NHW_v05')
plt.plot()
plt.plot(x_values,stra_counts_v05_uw[0,:], '-', color='red', label='NHW_v05_uw')
plt.plot()
plt.plot(x_values,stra_counts_ite132[0,:], '-', color='blue', label='NHW_ite132')
plt.plot()
plt.plot(x_values,stra_counts_v05[1,:], ':', color='black', label='NHC_v05')
plt.plot()
plt.plot(x_values,stra_counts_v05_uw[1,:], ':', color='red', label='NHC_v05_uw')
plt.plot()
plt.plot(x_values,stra_counts_ite132[1,:], ':', color='blue', label='NHC_ite132')
plt.plot()
plt.plot(x_values,stra_counts_v05[2,:], '--', color='black', label='NHE_v05')
plt.plot()
plt.plot(x_values,stra_counts_v05_uw[2,:], '--', color='red', label='NHE_v05_uw')
plt.plot()
plt.plot(x_values,stra_counts_ite132[2,:], '--', color='blue', label='NHE_ite132')
plt.plot()
plt.legend()
plt.xlabel('months')
plt.ylabel('pixel counts')
plt.title('Stratiform Counts - Near Equatorial, Northern Hemisphere')
plt.tight_layout()

In [52]:
# plot stratiform NHW output
fig = plt.figure()
#plt.xlim(1, 12)
#plt.ylim();
plt.plot(x_values,stra_counts_v05[0,:], '-', color='black', label='NHW_v05')
plt.plot()
plt.plot(x_values,stra_counts_v05_uw[0,:], '-', color='red', label='NHW_v05_uw')
plt.plot()
plt.plot(x_values,stra_counts_ite132[0,:], '-', color='blue', label='NHW_ite132')
plt.plot()
plt.legend()
plt.xlabel('months')
plt.ylabel('pixel counts')
plt.title('Stratiform Counts - NHW')
plt.tight_layout()

In [53]:
# plot stratiform NHC output
fig = plt.figure()
#plt.xlim(1, 12)
#plt.ylim();
plt.plot(x_values,stra_counts_v05[1,:], '-', color='black', label='NHC_v05')
plt.plot()
plt.plot(x_values,stra_counts_v05_uw[1,:], '-', color='red', label='NHC_v05_uw')
plt.plot()
plt.plot(x_values,stra_counts_ite132[1,:], '-', color='blue', label='NHC_ite132')
plt.plot()
plt.legend()
plt.xlabel('months')
plt.ylabel('pixel counts')
plt.title('Stratiform Counts - NHC')
plt.tight_layout()

In [54]:
# plot stratiform NHE output
fig = plt.figure()
#plt.xlim(1, 12)
#plt.ylim();
plt.plot(x_values,stra_counts_v05[2,:], '-', color='black', label='NHE_v05')
plt.plot()
plt.plot(x_values,stra_counts_v05_uw[2,:], '-', color='red', label='NHE_v05_uw')
plt.plot()
plt.plot(x_values,stra_counts_ite132[2,:], '-', color='blue', label='NHE_ite132')
plt.plot()
plt.legend()
plt.xlabel('months')
plt.ylabel('pixel counts')
plt.title('Stratiform Counts - NHE')
plt.tight_layout()

In [51]:
# plot other output
fig = plt.figure()
#plt.xlim(1, 12)
#plt.ylim();
plt.plot(x_values,other_counts_v05[0,:], '-', color='black', label='NHW_v05')
plt.plot()
plt.plot(x_values,other_counts_v05_uw[0,:], '-', color='red', label='NHW_v05_uw')
plt.plot()
plt.plot(x_values,other_counts_ite132[0,:], '-', color='blue', label='NHW_ite132')
plt.plot()
plt.plot(x_values,other_counts_v05[1,:], ':', color='black', label='NHC_v05')
plt.plot()
plt.plot(x_values,other_counts_v05_uw[1,:], ':', color='red', label='NHC_v05_uw')
plt.plot()
plt.plot(x_values,other_counts_ite132[1,:], ':', color='blue', label='NHC_ite132')
plt.plot()
plt.plot(x_values,other_counts_v05[2,:], '--', color='black', label='NHE_v05')
plt.plot()
plt.plot(x_values,other_counts_v05_uw[2,:], '--', color='red', label='NHE_v05_uw')
plt.plot()
plt.plot(x_values,other_counts_ite132[2,:], '--', color='blue', label='NHE_ite132')
plt.plot()
plt.legend()
plt.xlabel('months')
plt.ylabel('pixel counts')
plt.title('Other Counts - Near Equatorial, Northern Hemisphere')
plt.tight_layout()